### ISSUE TITLE
AF-FCL复现的bug：不存在.pkl文件

### ISSUE THREAD

**Issue by wangyingcan** [zaocan666/AF-FCL#1]
同学你好，我在AF-FCL中运行`python main.py --dataset EMNIST-Letters --data_split_file data_split/EMNIST_letters_split_cn8_tn6_cet2_cs2_s2571.pkl --num_glob_iters 60 --local_epochs 100 --lr 1e-4 --flow_lr 1e-4 --k_loss_flow 0.5 --k_flow_lastflow 0.4 --flow_explore_theta 0`命令时，出现了报错

`Traceback (most recent call last):
  File "main.py", line 98, in <module>
    main(args)
  File "main.py", line 30, in main
    run_job(args, args.seed)
  File "main.py", line 25, in run_job
    server = create_server_n_user(args, seed)
  File "main.py", line 16, in create_server_n_user
    server=FedPrecise(args, model, i)
  File "/home/wyc/AF-FCL/FLAlgorithms/servers/serverPreciseFCL.py", line 19, in __init__
    self.data = get_dataset(args, args.dataset, args.datadir, args.data_split_file)
  File "/home/wyc/AF-FCL/utils/dataset.py", line 118, in get_dataset
    with open(os.path.join(datadir, data_split_file), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/PreciseFCL/data_split/EMNIST_letters_split_cn8_tn6_cet2_cs2_s2571.pkl'`

在get_dataset函数读取.pkl文件时，找不到文件，请问这个文件时怎么生成的呢

**Comment by zaocan666** [comment]
可以用split_dataset.py文件生成
